name: HTTP Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: alphanav_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run database migrations
        run: npm run db:push
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/alphanav_test
          NODE_ENV: test
          
      - name: Run HTTP integration tests
        run: NODE_ENV=test tsx server/tests/security-http.test.ts
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/alphanav_test
          NODE_ENV: test
          SESSION_SECRET: test-session-secret-for-ci
          
      - name: Upload test results (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: |
            server/tests/**/*.log
            coverage/
          retention-days: 7
      
      - name: Test Summary
        if: always()
        run: |
          echo "## HTTP Integration Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ $? -eq 0 ]; then
            echo "✅ **All tests passed!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- 28/28 HTTP integration tests passing" >> $GITHUB_STEP_SUMMARY
            echo "- Multi-tenant security verified" >> $GITHUB_STEP_SUMMARY
            echo "- Authorization enforcement confirmed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Some tests failed**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please review the test output above for details." >> $GITHUB_STEP_SUMMARY
          fi
